apiVersion: v1
kind: ConfigMap
metadata:
  name: config-demo
  namespace: argocd-demo
data:
  single.properties: |-
    hello=nginx
  multiple.properties: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3
