apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-demo
  namespace: argocd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-demo
  template:
    metadata:
      labels:
        app: cm-demo
    spec:
      containers:
        - name: demo-pod
          image: nginx:1.25-alpine3.17-slim
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/properties
      volumes:
        - name: config-volume
          configMap:
            name: config-demo
            optional: true # mark the source ConfigMap as optional
